version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pictgram_app
    ports:
      - "8080:8080"
    # depends_on:
    #   - db
    # environment:
      # - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/your_database
      # - SPRING_DATASOURCE_USERNAME=your_username
      # - SPRING_DATASOURCE_PASSWORD=your_password

  # db:
  #   image: postgres:14
  #   container_name: pictgram_db
  #   environment:
  #     POSTGRES_DB: your_database
  #     POSTGRES_USER: your_username
  #     POSTGRES_PASSWORD: your_password
  #   ports:
  #     - "5432:5432"
    